### ISSUE TITLE
Feature Request: Settings "get" and "set" for a Sonos player

### ISSUE THREAD

**Issue by ianrathbone** [VonRehbergConsulting/n8n-nodes-sonos#1]
Hi thanks for making this excellent integration, I've been using it for some useful automation already.

Would it be possible to add the features for "settings" so I could get and set sonos player settings like mono mode?

https://developer.sonos.com/reference/control-api/settings/

**Comment by VonRehberg** [comment]
Hi Ian,
Thanks for the feedback! Sure extensions are possible ;-) I just wanted to stick to features, that are most probably used on a daily basis.
Can you elaborate a little bit more on your use case and why you would change settings of your speakers in an automation?
Thanks and regards,
Joschi

**Comment by ianrathbone** [comment]
Thank you!

So because we don't want to have the sound too loud at night we would turn speech enhancement on and night mode on.

What I would like to have is this reset the next day, so when we watch something in the day time it has both speech enhancement and night mode turned off! This is what the automation would do.

Hope that makes sense?

**Comment by VonRehberg** [comment]
Thanks for the example. Makes total sense to me!
I'm not sure, when we will have some spare time, but would be a good extension.
In case you cannot wait, feel free to contribute :-)

**Comment by VonRehberg** [comment]
This is probably the homeTheater options and not the player settings.
https://developer.sonos.com/reference/control-api/hometheater/setoptions/

Or would you see a real use case for speaker settings (stereo/mono, volume scaling, wifi)?

**Comment by ianrathbone** [comment]
Yes you're totally right I was looking at the wrong part of the docs!! 😬

I will definitely have a look to see if I can raise a PR for this thank you!

**Comment by VonRehberg** [comment]
It's implemented and published to version 1.1.1
