### ISSUE TITLE
Feature request: Text to speech (TTS)

### ISSUE THREAD

**Issue by Royal2000H** [VonRehbergConsulting/n8n-nodes-sonos#4]
This may be too cumbersome but I figured I'd ask.
In Home Assistant (HA), the Sonos integration allows you to announce things on your Sonos system by text. I'm not sure whether that would be possible here too. I realize this node works very differently compared to the HA integration, considering this node requires developer API and the HA integration does not, but perhaps it is still possible?

Why not just use Home Assistant then? I unfortunately don't have Home Assistant running in this location and it would not make sense to do so just for this purpose.

**Comment by VonRehberg** [comment]
Hey Roy,

Thanks for reaching out!
Unfortunately this is not something I may be looking into as it requires multiple parts to be implemented:
- text to speech
- store mp3 on a public disk

However you maybe able to implement this on your own without codig knowledge.
There are several text to speech APIs you could use, e.g.:
https://community.n8n.io/t/text-to-speech-openai/32697

Afterwards you could store the result mp3 where it's possible to access it by URL. In the end you just need to instruct Sonos to stream from a URL.

Hope that helps.
Joschi
