### ISSUE TITLE
Cannot Authenticate with SONOS

### ISSUE THREAD

**Issue by Royal2000H** [VonRehbergConsulting/n8n-nodes-sonos#5]
Hello,

I followed your authentication instructions, creating a developer account, generating credentials, copying the Redirect URI from n8n to Sonos, and copying the key and secret from Sonos to n8n.

Upon trying to authenticate the credentials, after logging in, the window performs the redirect but then n8n gives this error. I can confirm that I'm able to OAuth2 authenticate with other integrations such as the native Reddit integration.

![image](https://github.com/VonRehbergConsulting/n8n-nodes-sonos/assets/822546/4a7115e7-805c-48c0-96c4-a4e9c00b9902)

I've blurred the domain as it is not localhost. In case it's relevant to debugging, the redirect URL is over https.
Any thoughts regarding troubleshooting?

**Comment by VonRehberg** [comment]
Hey Roy,
Hard to tell. Just tested it on my end and it works fine. Are there any logs in the n8n container/console output?

**Comment by Royal2000H** [comment]
Thank you for your response!

In docker container log:
`Error: SONOS Error: Error: Unable to sign without access token`

In browser console:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

Only thing I can think of that's different than the GIF tutorial is that I'm using https://my.host.domain/ as opposed to http://localhost:port

**Comment by VonRehberg** [comment]
<img width="689" alt="Screenshot 2024-01-16 at 08 14 11" src="https://github.com/VonRehbergConsulting/n8n-nodes-sonos/assets/8611608/f67d1ddb-d3d9-4a6e-b75c-630c6ff465f0">

Are you using the correct access token URL?

**Comment by VonRehberg** [comment]
Looks like this part is missing in the setup documentation... 🫣

**Comment by Royal2000H** [comment]
Yes, I was. This is how I had it set up (the Access Token URL by default looks as below in my screenshot). It should pull the Client ID from the next field.

![image](https://github.com/VonRehbergConsulting/n8n-nodes-sonos/assets/822546/0ee7e227-bc1d-42be-88f7-5506a2bba3b7)

I also replaced `${clientId}` with the Client ID in the access token URL (as per your screenshot) but that did not fix it.

**Comment by iggyvanlith** [comment]
For me it worked by replacing both `${clientId}` and `${clientSecret}` by the actual id and and secret you also paste in the next fields. Seems like it isn't replacing them automatically.

**Comment by VonRehberg** [comment]
Closing this issue as it seems to be solved.
